Update dates
CyberDiscovery/cyberdisc-bot pull request #588
Opened 2020-11-12 20:11 UTC by thebeanogamer

2020-11-12 20:12 UTC, Sh3llcod3 approved these changes

2020-11-14 10:13 UTC, H4ckerJ4cker approved these changes

2020-12-06 12:21 UTC, Sh3llcod3 approved these changes

2020-12-10 12:20 UTC, Sh3llcod3 approved these changes

2020-12-18 20:54 UTC, david-cooke requested changes
delete the server

2020-12-18 20:54 UTC, Bentechy66 requested changes
why not just delete the bot? seems easier imo

2020-12-18 20:54 UTC, Trefonix approved these changes

2020-12-18 21:05 UTC, merged